name: avatar_brick
description: A Customized Avatar Widget.
version: 0.1.0
homepage: https://github.com/congson99
repository: https://github.com/congson99

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0